### ISSUE TITLE
在unocss的0.22.4版本中，childs还未没加入呢

### ISSUE THREAD

**Issue by 729902288** [antfu/unocss#515] opened 2022-01-19 02:08 UTC
由于variant中的children与react的这个属性冲突， 在unocss的0.22.4版本中，childs还未没加入呢
![image](https://user-images.githubusercontent.com/20468762/150050201-6b411c19-7d2c-4d56-b76d-aff61b31d111.png)

https://unocss.antfu.me/?html=DwVwNgBAxgFglgEzAZwLwHIBGBzAtJsEAU1wBYAGciZABwEMoSBPXAJnQD4AoCCYMOBwBmcAE7IALsAD0A7r36DkRKAHsAdghlyefORJiiiRbYK6gwHIA&config=Q&options=N4IgzgLgTglgxhEAuaBXApgXyA

**Comment by hannoeru** [comment] 2022-01-19 03:32
Duplicate of #500, open a new issue with change to `uno-children` or Draft a new PR.

**Closed by hannoeru** 2022-01-19 03:32 UTC

**Comment by antfu** [comment] 2022-01-19 05:33
It's closed without merging, I have already explained that. `un-` prefix will always work when that you can use to avoid conflicts
https://unocss.antfu.me/?html=DwEwlgbgBArgdgWgMYAswBsQCcCmcC8ARAA4BMhAfAFDAD04EFQA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHE6kAlEA&options=N4IgzgLgTglgxhEAuAZgQwDZgKYF8g
