### ISSUE TITLE
Rotation creates an outline which suffers from aliasing (@unocss/preset-icons)

### ISSUE THREAD

**Issue by kreha1** [antfu/unocss#300] opened 2021-12-23 00:12 UTC
AFAIK this happens only in Firefox, and that would probably mean there's nothing that can be done to fix it, as it stems from the way Firefox implements rotation for in-style icons.
https://user-images.githubusercontent.com/3883601/147168705-a38fbd7e-c3f5-4657-bc43-fec99539245f.mp4

The curious thing is, that this can be only observed on monochrome icons (from various icon packs):
![image](https://user-images.githubusercontent.com/3883601/147168692-c47676e5-5c92-4da4-919f-bfd78e9c6be2.png)

Still, I thought it's worth pointing out, as that would be one weakness of CSS based icons (at least for Firefox users)

**Comment by userquin** [comment] 2021-12-23 18:56
@antfu @kreha1 what if you can force  `background-img` some icons? for example: 
```html
<div class="w-100vw flex flex-col items-center gap-y-1em my-1em">
  <div class="i-mdi-buffer?bg w-4rem h-4rem animate-spin animate-3s"></div>
  <div class="i-mdi-buffer?mask w-4rem h-4rem  animate-spin animate-3s"></div>
</div>
```

with this result:

https://imgur.com/KPIGhai

**Comment by userquin** [comment] 2021-12-23 18:58
![imagen](https://user-images.githubusercontent.com/6311119/147281926-d4f4d6a5-7416-43ef-8062-b81416e837ee.png)

**Comment by antfu** [comment] 2021-12-24 04:11
[Playground Repro](https://unocss.antfu.me/?html=DwEwlgbgBAxgNgQwM5ILwCIDuBaAjABnwkygDM4BTADzMquxgHs4owAXCgWyQYoDsOAJygBzBAAdsATzxconGbi7oAfACgoUUJFiIUGMNk7hsAIwCupUhWE4ALILkALbA%2BUrgAenAR1m7dDwyGjohsaGFlY2UPaOnFAubvGCjGwIHHj4ql4%2B6jmQKkA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHCjjUrAFxwA2itV6A9AD1mBGKiwwAtAB1dCgHQAqAJR2AugBIjAGjgFXQDzaysYTzc4AF4APkCkUMtrHQApAGUAeQA5J1YYKGwiYHQATwUk8KjSN08-A09OGqA&options=N4IgzgLgTglgxhEAuAZgQwDZgKYF8g)

**Comment by antfu** [comment] 2021-12-24 04:14
@userquin your proposal is something nice to have, but not the fix to this issue, since when you use the background mode you lost the ability to color the icon. I would think this is more like a Firefox bug as there seems nothing we could do to workaround it.

**Comment by antfu** [comment] 2021-12-24 04:17
The only workaround I can see it to wrap with a parent container to clip out the border:

```html
  <div class="rotate-10 overflow-hidden">
    <div class="i-mdi-buffer w-4rem h-4rem scale-101 origin-center"></div>
  </div>
```

[Playground](https://unocss.antfu.me/?html=DwEwlgbgBAxgNgQwM5ILwCIDuBaAjABnwkygDM4BTADzMquxgHs4owAXCgWyQYoDsOAJygBzBAAdsATzxconGbi7oAfACgoUUJFiIUGMNk7hsAIwCupUhWE4ALILkALbA%2BUrgAenAR1m7dDwyGjogoxsCBx4%2BFCMEDbkjDhOYCAg-Koamlo%2BusEGRiYWVjZQ9o6cUC5ulUgwCJTRuLGCYCJgfLwCNqpePn5a3pDqfcNAA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHCjjUrAFxwA2itV6A9AD1mBGKiwwAtAB1dCgHQAqAJR2AugBIjAGjgFXQDzaysYTzc4AF4APkCkUMtrHQApAGUAeQA5J1YYKGwiYHQATwUk8KjSN08-A09OGqA&options=N4IgzgLgTglgxhEAuAZgQwDZgKYF8g)

**Comment by userquin** [comment] 2021-12-24 09:40
@antfu the problem is with `animate-spin` not with `rotate`: with your approach the border still there:

[Playground](https://unocss.antfu.me/?html=DwEwlgbgBAxgNgQwM5ILwCIDuBaAjABnwkygDM4BTADzMquxgHs4owAXCgWyQYoDsOAJygBzBAAdsATzxconGbi7oAfACgoUUJFiIUGMNk7hsAIwCupUhWE4ALILkALbA%2BUrgAenAR1m7dDwyGjojBA25Iw4TmAgIPyqGppaPrrBBkYmFlY2UEgwCJR4%2BLhQjIJgImB8vAK59o6cUC5uTQh8YJwIHNhI4tVQ7Z3dFNgAzEiqXj5%2BWt6Q6tMLQA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHCjjUrAFxwA2itV6A9AD1mBGKiwwAtAB1dCgHQAqAJR2AugBIjAGjgFXQDzaysYTzc4AF4APkCkUMtrHQApAGUAeQA5J1YYKGwiYHQATwUk8KjSN08-A09OGqA&options=N4IgzgLgTglgxhEAuAZgQwDZgKYF8g)

**Comment by userquin** [comment] 2021-12-24 16:02
@kreha1 as a workaround, can you test with this (`preserve-3d` do the trick)? You need to wrap the icon:
```html
  <div class="animate-spin animate-3s preserve-3d w-4em h-4em color-red-400">
    <div class="i-mdi-buffer w-4em h-4em"></div>
  </div>
```

**Comment by kreha1** [comment] 2021-12-24 17:14
@userquin Thank you, I will test this solution, once I have access to my laptop. I will let you know, probably next day.

**Comment by kreha1** [comment] 2021-12-25 10:59
Ok, this looks good. Thank you, @userquin, for the workaround.

**Comment by userquin** [comment] 2021-12-25 12:59
Closing this since as it is a problem with Firefox and the workaround seems to work. We cannot do more about it here...

**Closed by userquin** 2021-12-25 12:59 UTC
