### ISSUE TITLE
presetAttributify inoperative

### ISSUE THREAD

**Issue by gggso** [antfu/unocss#291] opened 2021-12-22 06:25 UTC
![image](https://user-images.githubusercontent.com/6212790/147045625-2a7fe2c4-0baa-4e21-b95d-d7079bd17bad.png)

"vite": "^2.7.2",
"react": "^17.0.2",
"unocss": "^0.16.4",
"@unocss/preset-attributify": "^0.16.4",
nodejs: v16.13.1

**Comment by 729902288** [comment] 2021-12-22 06:36
You try it，sets like this:
presets:[
    presetUno(),
    presetAttributify(),
    presetIcons(),
 ],

**Comment by gggso** [comment] 2021-12-22 06:39
> 

![image](https://user-images.githubusercontent.com/6212790/147047245-6f6f7475-a01c-4e51-9f3a-0e17acc6f81d.png)
fail

**Comment by antfu** [comment] 2021-12-22 07:48
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2021-12-22 07:48 UTC

**Comment by gggso** [comment] 2021-12-22 08:18
> We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

1、pnpm create vite unocss-demo -- --template react-ts
2、cd unocss-demo && pnpm i
3、pnpm i -D unocss @unocss/preset-attributify @unocss/preset-uno @unocss/preset-icons
4、vite.config.ts add `import Unocss from 'unocss/vite'
import { presetUno, presetIcons, presetAttributify } from 'unocss'` `    Unocss({
      presets: [presetUno(), presetAttributify(), presetIcons()],
    }),`
5、main.tsx add `import 'uno.css'`
6、App.tsx add `<button class="bg-blue-400 hover:bg-blue-500 text-sm text-white font-mono font-light py-2 px-4 rounded border-2 border-blue-200 dark:bg-blue-500 dark:hover:bg-blue-600">
  Button
</button>` and  `<button 
  bg="blue-400 hover:blue-500 dark:blue-500 dark:hover:blue-600"
  text="sm white"
  font="mono light"
  p="y-2 x-4"
  border="2 rounded blue-200"
>
  Button
</button>`
7、pnpm run dev
![image](https://user-images.githubusercontent.com/6212790/147059295-0ea00f55-9af9-496f-9efb-ed0df856dc93.png)

**Comment by userquin** [comment] 2021-12-22 12:08
@antfu once added the branch/PR for `vite-react` I'll include some hints on docs about this and using the `shadow-dom`, add a new section for frameworks before/after inspector?

@gggso you need to add the `react` plugin after `unocss` plugin, it seems there is some problem if `react` is added before `unocss`.

I'm adding a `test/fixtures/vite-react` example to the repo.

![imagen](https://user-images.githubusercontent.com/6311119/147090328-fba654b3-58f0-4c1a-86b9-49a6ef3fd0ea.png)

**Comment by gggso** [comment] 2021-12-23 00:45
@userquin Thank you

**Comment by userquin** [comment] 2021-12-23 11:26
@gggso I'll test it also using also `@vitejs/plugin-react-refresh` instead `@vitejs/plugin-react`, maybe with this another plugin we can, stay turned...

**Comment by userquin** [comment] 2021-12-23 12:15
@gggso with `@vitejs/plugin-react-refresh` also works, and you don't need to refresh the page, I'll update the `test/fixture/vite-react` to work with both, just check the `package.json` scripts.

**Comment by gggso** [comment] 2021-12-27 06:35
@gggso thanks again，Have you noticed that access on the phone is blank
